#!/bin/bash

OS_CLUSTERS_BASE_DIR=${OS_CLUSTERS_BASE_DIR:=$HOME}
KUBECONFIG=${KUBECONFIG:=$HOME}
AUTH_DIR="/auth"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -v|--version)
    VERSION_SUFFIX="-$2"
    shift # past argument
    shift # past value
    ;;
    -l|--late)
    DIR_SUFFIX="-late"
    shift # past argument
    ;;
    -d|--download)
    INSTALL_DIR=${HOME}/downloads
    AUTH_DIR=""
    mv "${HOME}/downloads/kubeconfig (1)" ${HOME}/downloads/kubeconfig
    mv "${HOME}/downloads/kubeadmin-password (1)" ${HOME}/downloads/kubeadmin-password
    shift # past argument
    shift # past value
    ;;
    --last)
    cp ${KUBECONFIG_DIR}/kubeconfig.last ${KUBECONFIG_DIR}/kubeconfig
    cp ${KUBECONFIG_DIR}/kubeadmin-password.last ${kubeadmin-password}/kubeconfig
    exit
    ;;
    --special)
    INSTALL_DIR=${INSTALL_DIR:=$OS_CLUSTERS_BASE_DIR/clusters/cluster-manual-special}
    shift # past argument
    ;;
    *)    # unknown option
    shift # past argument
    ;;
esac
done

# set -euxo pipefail

INSTALL_DIR=${INSTALL_DIR:=$OS_CLUSTERS_BASE_DIR/clusters/cluster-manual}${VERSION_SUFFIX}${DIR_SUFFIX}

cp ${KUBECONFIG_DIR}/kubeconfig ${KUBECONFIG_DIR}/kubeconfig.last
cp ${KUBECONFIG_DIR}/kubeadmin-password ${KUBECONFIG_DIR}/kubeadmin-password.last

cp ${INSTALL_DIR}${AUTH_DIR}/kubeconfig ${KUBECONFIG_DIR}/kubeconfig
cp ${INSTALL_DIR}${AUTH_DIR}/kubeadmin-password ${KUBECONFIG_DIR}/kubeadmin-password

